{% set name = "json_schema_validator" %}
{% set version = "2.1.0" %}
{% set sha256 = "83f61d8112f485e0d3f1e72d51610ba3924b179926a8376aef3c038770faf202" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pboettch/json-schema-validator/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - nlohmann_json
  run:
    - nlohmann_json

test:
  commands:
    - test -f ${PREFIX}/include/json-schema.hpp  # [unix]
    - test -f ${PREFIX}/lib/libjson-schema-validator.so  # [unix]

about:
  home: https://github.com/pboettch/json-schema-validator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON schema validator for JSON for Modern C++

extra:
  recipe-maintainers:
    - asafkahlon
